-- MySQL Script generated by MySQL Workbench
-- 04/05/18 23:42:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema spring_shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema spring_shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spring_shop` DEFAULT CHARACTER SET utf8 ;
USE `spring_shop` ;

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `id_user` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(200) NOT NULL COMMENT '',
  `enabled` INT(11) NOT NULL DEFAULT '1' COMMENT '',
  PRIMARY KEY (`id_user`)  COMMENT '',
  UNIQUE INDEX `username_UNIQUE` (`username` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `authority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `authority` (
  `id_authority` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `id_user` INT(11) NOT NULL COMMENT '',
  `role` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_authority`)  COMMENT '',
  UNIQUE INDEX `idx_username_role` (`id_user` ASC, `role` ASC)  COMMENT '',
  INDEX `fk_username_idx` (`id_user` ASC)  COMMENT '',
  CONSTRAINT `fk_authority_id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `order_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `order_details` (
  `id_order` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `surname` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `address` VARCHAR(450) NULL DEFAULT NULL COMMENT '',
  `phone` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id_order`)  COMMENT '',
  UNIQUE INDEX `id_order_UNIQUE` (`id_order` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product` (
  `id_product` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `price` DOUBLE NULL DEFAULT '0' COMMENT '',
  `description` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `quantity` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`id_product`)  COMMENT '',
  UNIQUE INDEX `idproduct_UNIQUE` (`id_product` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cart_entry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cart_entry` (
  `id_cart_entry` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `id_product` INT(11) NOT NULL COMMENT '',
  `quantity` INT(11) NOT NULL DEFAULT '1' COMMENT '',
  `id_order` INT(11) NULL DEFAULT NULL COMMENT '',
  `id_user` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id_cart_entry`)  COMMENT '',
  INDEX `fk_id_product_idx` (`id_product` ASC)  COMMENT '',
  INDEX `fk_id_order_idx` (`id_order` ASC)  COMMENT '',
  INDEX `fk_cart_entry_id_user_idx` (`id_user` ASC)  COMMENT '',
  CONSTRAINT `fk_cart_entry_id_order`
    FOREIGN KEY (`id_order`)
    REFERENCES `order_details` (`id_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_entry_id_product`
    FOREIGN KEY (`id_product`)
    REFERENCES `product` (`id_product`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_entry_id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
